name: Deploy
on:
    push:
#        branches:
#            - main

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    DO_NOT_TRACK: 1
    TURBO_TELEMETRY_DISABLED: 1

jobs:
    deploy:
        runs-on: ubuntu-latest
        timeout-minutes: 10

        steps:
            ##########################################################################
            # Setup
            -   uses: actions/checkout@v3

            # Setup TS
            -   uses: actions/setup-node@v3
                with:
                    node-version: 22
                    architecture: "x64"
                    cache: "npm"
                    cache-dependency-path: package-lock.json

            # Install npm dependencies
            -   name: Install node_modules
                run: |
                    npm install

            # Setup Python
            -   uses: actions/setup-python@v4
                with:
                    python-version: "3.12"

            -   name: Install uv
                uses: astral-sh/setup-uv@v5

            ##########################################################################
            # Build
            -   name: Build apps
                run: |
                    npm run build                    
